In [1]:
from keras.preprocessing.text import one_hot

In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'Undestand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Undestand the meaning of words',
 'your videos are good']

In [7]:
voc_size=10000

## One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[7832, 2989, 7580, 7941], [7832, 2989, 7580, 6739], [7832, 7322, 7580, 6492], [5724, 9311, 5618, 4078, 3039], [5724, 9311, 5618, 4078, 5336], [7184, 7832, 8581, 7580, 138], [6293, 8231, 8518, 4078]]


## Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7832 2989 7580 7941]
 [   0    0    0    0 7832 2989 7580 6739]
 [   0    0    0    0 7832 7322 7580 6492]
 [   0    0    0 5724 9311 5618 4078 3039]
 [   0    0    0 5724 9311 5618 4078 5336]
 [   0    0    0 7184 7832 8581 7580  138]
 [   0    0    0    0 6293 8231 8518 4078]]


In [14]:
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123
   -0.03049912 -0.04946909  0.0096568   0.0057041  -0.03210561]
  [ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123
   -0.03049912 -0.04946909  0.0096568   0.0057041  -0.03210561]
  [ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123
   -0.03049912 -0.04946909  0.0096568   0.0057041  -0.03210561]
  [ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123
   -0.03049912 -0.04946909  0.0096568   0.0057041  -0.03210561]
  [ 0.04943962  0.03835689 -0.00197797 -0.01352141 -0.0229033
    0.01306658  0.00631382 -0.027557   -0.0428458   0.04571024]
  [ 0.01414248 -0.03155667 -0.01455815  0.03425578  0.00121896
    0.04303271  0.01425963 -0.04468761  0.04856657  0.01940826]
  [ 0.03001783 -0.04733617 -0.04549487 -0.03624894 -0.0495287
    0.0445809   0.04697814  0.01424957  0.01611248 -0.04390405]
  [-0.02384876 -0.00623053  0.0071162  -0.00555329  0.04084739
    0.03169817  0.02688844 -0.03697883 -0.03309961

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 7832, 2989, 7580, 7941])

In [19]:
print(model.predict(embedded_docs)[0])

[[ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123 -0.03049912
  -0.04946909  0.0096568   0.0057041  -0.03210561]
 [ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123 -0.03049912
  -0.04946909  0.0096568   0.0057041  -0.03210561]
 [ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123 -0.03049912
  -0.04946909  0.0096568   0.0057041  -0.03210561]
 [ 0.03810592 -0.00842856  0.03336282 -0.02111099  0.00454123 -0.03049912
  -0.04946909  0.0096568   0.0057041  -0.03210561]
 [ 0.04943962  0.03835689 -0.00197797 -0.01352141 -0.0229033   0.01306658
   0.00631382 -0.027557   -0.0428458   0.04571024]
 [ 0.01414248 -0.03155667 -0.01455815  0.03425578  0.00121896  0.04303271
   0.01425963 -0.04468761  0.04856657  0.01940826]
 [ 0.03001783 -0.04733617 -0.04549487 -0.03624894 -0.0495287   0.0445809
   0.04697814  0.01424957  0.01611248 -0.04390405]
 [-0.02384876 -0.00623053  0.0071162  -0.00555329  0.04084739  0.03169817
   0.02688844 -0.03697883 -0.03309961 -0.03256798]]
